name: society_security_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^6.2.1
  flexible_scrollbar: ^0.1.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
